const SortType = {
  DEFAULT: 'default',
  DATE: 'date',
  RATING: 'rating',
};

const COMMENTS_EMOTIONS = [
  'smile',
  'sleeping',
  'puke',
  'angry'
];

const DEFAULT_RENDERED_FILMS_QUANTITY = 5;
const FILMS_TO_RENDER_QUANTITY = 5;

const FILM_CARD_DATE_FORMAT = 'YYYY';
const FILM_POPUP_DATE_FORMAT = 'D MMM YYYY';

export { SortType, COMMENTS_EMOTIONS, DEFAULT_RENDERED_FILMS_QUANTITY, FILMS_TO_RENDER_QUANTITY, FILM_CARD_DATE_FORMAT, FILM_POPUP_DATE_FORMAT };

